#!/bin/bash
clear
    echo -e "\033[01;31m\033[1;31m\033[5;34;47m                      FIREWALL                      \033[1;33m \033[0m\033[01;31m║"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➩  \033[1;33mADICIONAR PORTA \033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➩  \033[1;33mREMOVER PORTA \033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➩  \033[1;33mLISTA DE PORTAS ABERTAS  \033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"

echo -e "\033[01;31m\033[0m"
			
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			
			clear
			case $x in
			1 | 01)
			lup=""
			while [ -z $lup ]
			do
			clear
			echo "SELECIONE O PROTOCOLO DA PORTA A SER ADICIONADA

1. TCP
2. UDP

0. Voltar
"
read -p "Digite a Opcao desejda: " op

case $op in
1 | 01)
  clear
  read -p "Digite a Porta TCP: " tc
  firewall-cmd --zone=public --permanent --add-port=$tc/tcp
  firewall-cmd --reload
;;

2 | 02)
 clear
 read -p "Digite a Porta UDP: " ud
 firewall-cmd --zone=public --permanent --add-port=$ud/udp
 firewall-cmd --reload
;;
0 | 00)
lup=[$lup+1]
fr
;;

*)
echo -e " Opcao Invalida "
sleep 2
;;

esac
done
;;

		2 | 02)

              lup1=""
              while [ -z $lup1 ]
              do
              clear
              echo "SELECIONE O PROTOCOLO DA PORTA A SER REMOVIDA

1. TCP
2. UDP

0. Voltar

 " 

read -p "Digite a Opcao desejda: " op1 
case $op1 in
1 | 01)
  clear
  read -p "Digite a Porta TCP: " tc
  firewall-cmd --zone=public --permanent --remove-port=$tc/tcp
  firewall-cmd --reload
;;


2 | 02)
 clear
 read -p "Digite a Porta UDP: " ud
 firewall-cmd --zone=public --permanent --remove-port=$ud/udp
 firewall-cmd --reload 
;; 
0 | 00) 
lup1=[$lup1+1] 
fr
;;
*)
clear
echo -e " Opcao Invalida " 
sleep 2
;; 
esac 
done
;;


		3 | 03)
		clear
		lup2=""
		while [ -z $lup2 ]
		do
		clear
		echo -e "LISTA DE PORTAS ABERTAS"
		echo
		echo -e "$(firewall-cmd --zone=public --list-port)"
		echo
		read -p "Digite [0] Para Voltar: " v
		case $v in
		0 | 00)
		lup2=[lup2+1]
		fr
		;;
		*)
		clear
		echo -e "Opcao Invalida"
		sleep 2
		;;
		esac
		done
		;;

		0 | 00)
		clear
		menu
		;;
		*)
		clear
		echo -e "Opcao Invalida"
		sleep 2
		fr
		;;
esac
