#!/bin/bash
    clear
    echo -e "\033[01;31m\033[1;31m\033[5;34;47m                      FERRAMENTAS                      \033[1;33m \033[0m\033[01;31m║"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➩  \033[1;33mSWAPMEMORY \033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➩  \033[1;33mMONITORAR SISTEMA COMPLETO \033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➩  \033[1;33mMONITORAR BANDA POR PROCESSOS \033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[01;31m\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			swapmemory
			;;
			2 | 02)
			clear
			echo -e "\033[1;33mPARA SAIR CLICK CTRL + C\033[1;36m"
			sleep 5s
			if [ -z $(which htop) ]
			then
			apt install htop -y && htop
			else
			htop
			fi
			;;
			3 | 03)
			clear
			echo -e "\033[1;33mPARA SAIR CLICK CTRL + C\033[1;36m"
			sleep 5s
			if [ -z $(which glances) ]
			then
			apt install glances -y && glances
			else
			glances
			fi
			;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
